# Generated by Django 4.2.13 on 2026-05-25 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('approve', 'Approved'), ('reject', 'Rejected'), ('flag', 'Flagged'), ('unflag', 'Unflagged'), ('edit', 'Edited'), ('lock', 'Locked for Audit'), ('bulk_approve', 'Bulk Approved')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('changes', models.JSONField(default=dict)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('emission_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_decisions', to='emissions.emissionrecord')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
    ]
