# Generated by Django 4.2.13 on 2026-05-25 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('scope', models.CharField(choices=[('1', 'Scope 1'), ('2', 'Scope 2'), ('3', 'Scope 3')], max_length=1)),
                ('factor_value', models.DecimalField(decimal_places=8, max_digits=20)),
                ('factor_unit', models.CharField(max_length=50)),
                ('activity_unit', models.CharField(max_length=20)),
                ('source_name', models.CharField(max_length=255)),
                ('source_year', models.IntegerField()),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('co2_factor', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('ch4_factor', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('n2o_factor', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-source_year', 'source_type'],
            },
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap', 'SAP'), ('utility', 'Utility'), ('travel', 'Travel')], max_length=20)),
                ('scope', models.CharField(choices=[('1', 'Scope 1'), ('2', 'Scope 2'), ('3', 'Scope 3')], max_length=1)),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(blank=True, max_length=100)),
                ('activity_description', models.TextField()),
                ('activity_value', models.DecimalField(decimal_places=6, max_digits=20)),
                ('activity_unit', models.CharField(max_length=20)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('co2_kg', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('ch4_kg', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('n2o_kg', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('facility', models.CharField(blank=True, max_length=255)),
                ('cost_center', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('suspicious_reasons', models.JSONField(default=list)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('was_edited', models.BooleanField(default=False)),
                ('original_values', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emission_factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='emissions.emissionfactor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='core.organization')),
                ('raw_record', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='emission_record', to='ingestion.rawrecord')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start', '-created_at'],
                'indexes': [models.Index(fields=['organization', 'scope', 'status'], name='emissions_e_organiz_35327c_idx'), models.Index(fields=['organization', 'source_type', 'period_start'], name='emissions_e_organiz_5f0dcd_idx'), models.Index(fields=['is_suspicious', 'status'], name='emissions_e_is_susp_14c38b_idx'), models.Index(fields=['organization', 'period_start', 'period_end'], name='emissions_e_organiz_0cdeb0_idx')],
            },
        ),
    ]
